module4-task2
lable01/six-cities pull request #4
Opened 2024-03-11 19:33 UTC by lable01

добавил форму

2024-03-12 17:46 UTC, Finnko requested changes

2024-03-12 19:16 UTC, lable01 commented on src/components/offer-details/offer-details.tsx
> +                <ReviewsInfo />
принял, понял, в принципе это достаточно логично

2024-03-12 19:19 UTC, lable01 commented on src/components/offer-details/offer-details.tsx
>                    </div>
ага, я про эти моки совсем забыл

2024-03-12 19:31 UTC, lable01 commented on src/components/offer-details/offer-details.tsx
>                    <span className="reviews__user-name">Max</span>
готово

2024-03-12 19:42 UTC, lable01 commented on src/components/reviews-form/reviews-form.tsx
> +    const { name, value } = event.currentTarget;
готово, допом привел типы иначе была ошибка

2024-03-12 19:45 UTC, lable01 commented on src/components/reviews-form/reviews-form.tsx
> +          with at least <b className="reviews__text-amount">50 characters</b>.
готово

2024-03-12 19:49 UTC, lable01 commented on src/components/reviews-form/reviews-form.tsx
> +          disabled={review.review.length < 50 || review.rating === 0}
готово

2024-03-12 20:20 UTC, lable01 commented on src/components/reviews-info/reviews-info.tsx
> +  );
готово

2024-03-15 12:28 UTC, Finnko commented on src/components/offer-details/offer-details.tsx
> +                <ReviewsInfo key={review.userUrl} review={review} />
У ревью будет id его и надо в качестве ключа использовать

2024-03-15 12:28 UTC, Finnko commented on src/components/reviews-form/reviews-form.tsx
> +    review.review.length > 300 ||
50/300 стоит вынести в объект констнатный

2024-03-15 12:28 UTC, Finnko commented on src/utils/function.ts
> +function getCurrentDate(date: Date, isDay: boolean) {
Более гибкое решение прокидывать формат вторым параметром, сделав какой-то более популярный значением по умолчанию, иначе с появлением 3 формата тебе придется писать еще иф

2024-03-15 12:28 UTC, Finnko commented on src/utils/function.ts
> +  }
if отделяем пустой строкой

2024-03-15 12:28 UTC, Finnko commented on src/utils/function.ts
> +  return `${width}%`;
return также

2024-03-15 12:28 UTC, Finnko commented on src/utils/function.ts
> +  const width = (100 / 5) * stars;
Вынеси 5 в константу, если вдруг рейтинг станет 10 звездочным тебе надо будет изменить 1 константу

2024-03-15 12:28 UTC, Finnko commented on src/utils/function.ts
> +function getStarsWidth(stars: number) {
Правильное название для входящего параметра это rating так как именно его значение ты получаешь

2024-03-15 12:28 UTC, Finnko commented on src/types/review.ts
> +export type TReview = {
- [ ] добавить id

2024-03-15 12:28 UTC, Finnko commented on src/pages/not-found/not-found.tsx
> +      </Helmet>
title на английском языке дальше текст на русском, надо определиться, учитывая что почти вся разметка на англ ответ очевиден

2024-03-15 12:28 UTC, Finnko commented on src/const.ts
> +export const ReviewsCharacters = 50;
Не увидел где это используется и почему только 50

2024-03-15 12:28 UTC, Finnko commented on src/const.ts
> +export const StarsWidth = ['0%', '20%', '40%', '60%', '80%', '100%'];
Удалить

2024-03-15 12:28 UTC, Finnko commented on src/const.ts
> +export const ReviewsCharacters = 50;
Нейминг для констант

2024-03-15 12:28 UTC, Finnko commented on src/components/reviews-info/reviews-info.tsx
> +  const { name, stars, date, userUrl, comment } = review;
поля stars в ревью не будет, посмотри по спеке что приходит, чтобы не писать адаптер

2024-03-17 18:58 UTC, lable01 commented on src/components/offer-details/offer-details.tsx
> +                <ReviewsInfo key={review.userUrl} review={review} />
Хз, там вроде айди одинаковый будет для всех

2024-03-17 19:02 UTC, lable01 commented on src/components/reviews-form/reviews-form.tsx
> +    review.review.length > 300 ||
Готово

2024-03-17 19:05 UTC, lable01 commented on src/utils/function.ts
> +function getCurrentDate(date: Date, isDay: boolean) {
готово

2024-03-17 19:07 UTC, lable01 commented on src/utils/function.ts
> +  }
правило преттиера так настроено, оставлю или менять?

2024-03-17 19:07 UTC, lable01 commented on src/utils/function.ts
> +  return `${width}%`;
готово

2024-03-17 19:08 UTC, lable01 commented on src/pages/not-found/not-found.tsx
> +      </Helmet>
готово

2024-03-17 19:11 UTC, lable01 commented on src/const.ts
> +export const ReviewsCharacters = 50;
готово, убрал, завел константный объект с минимальым и максимальным значением отзыва

2024-03-17 19:11 UTC, lable01 commented on src/const.ts
> +export const ReviewsCharacters = 50;
удалил константу

2024-03-17 19:13 UTC, lable01 commented on src/const.ts
> +export const StarsWidth = ['0%', '20%', '40%', '60%', '80%', '100%'];
удалил, хз что тут делала эта константа

2024-03-17 19:13 UTC, lable01 commented on src/components/reviews-info/reviews-info.tsx
> +  const { name, stars, date, userUrl, comment } = review;
поменял

2024-03-22 07:25 UTC, Finnko commented on src/components/favorite-page-component/favorites-block/favorites-block.tsx
> +import { TListItemProps } from 'components/main-full/main-full.tsx';
Делаешь лишнюю зависимость на main full, вынеси тип в папку types если он используется в нескольких местах

2024-03-22 07:25 UTC, Finnko commented on src/components/favorite-page-component/favorites-block/favorites-block.tsx
> +  const favoriteOffersByCity: { [key: string]: TListItemProps } = offers.reduce(
каст типа надо убрать и написать reduce<{ [key: string]: TListItemProps }>

2024-03-22 07:25 UTC, Finnko approved these changes

2024-03-22 07:26 UTC, merged